name: fff
version: 0.0.1
author: Viktor Dakalov <atlantidu@gmail.com>
description: Dart package for convenient work with color
homepage: https://github.com/vdakalov/fff
dev_dependencies:
  unittest: any
